import 'server-only';
import { mkdir, rm } from 'node:fs/promises';
import { EventEmitter } from 'node:events';
import path from 'node:path';
import makeWASocket, { DisconnectReason, fetchLatestBaileysVersion, makeCacheableSignalKeyStore, useMultiFileAuthState, type WASocket, type WAMessage } from '@whiskeysockets/baileys';
import QRCode from 'qrcode';
import { prepareMedia } from './media';
import { whatsappLog } from './logger';
import type { Contact, SendMediaInput, SendTextInput, WhatsAppDiagnostics, WhatsAppState } from './types';

const authDirectory = () => process.env.WHATSAPP_AUTH_DIR || path.join(process.cwd(), '.whatsapp-auth');
const normalizeJid = (value: string) => value.includes('@') ? value : `${value.replace(/\D/g, '')}@s.whatsapp.net`;
const initialState = (): WhatsAppState => ({ status: 'disconnected', qr: null, qrExpiresAt: null, connectedAt: null, authenticatedAt: null, phone: null, profileName: null, profilePhoto: null, lastError: null, lastSyncedAt: null, reconnectAttempts: 0, platformVersion: null, deliveryStatus: null, deliveryMessage: null, updatedAt: new Date().toISOString() });

class WhatsAppManager {
  private socket: WASocket | null = null; private state = initialState(); private readonly events = new EventEmitter(); private startPromise: Promise<void> | null = null; private reconnectTimer: NodeJS.Timeout | null = null; private qrTimer: NodeJS.Timeout | null = null; private reconnectAttempts = 0; private readonly contacts = new Map<string, Contact>(); private readonly messages = new Map<string, WAMessage>();
  getState = () => ({ ...this.state, qr: this.state.qr });
  getQr = () => this.state.qr ? { qr: this.state.qr, expiresAt: this.state.qrExpiresAt } : null;
  getContacts = () => [...this.contacts.values()];
  getDiagnostics = (): WhatsAppDiagnostics => ({ uptimeSeconds: this.state.connectedAt ? Math.max(0, Math.floor((Date.now() - Date.parse(this.state.connectedAt)) / 1000)) : 0, sessionAgeSeconds: this.state.authenticatedAt ? Math.max(0, Math.floor((Date.now() - Date.parse(this.state.authenticatedAt)) / 1000)) : 0, reconnectAttempts: this.reconnectAttempts, socketHealthy: !!this.socket && this.state.status === 'connected', authenticationHealthy: !!this.state.authenticatedAt && this.state.status !== 'authentication_failed' && this.state.status !== 'logged_out', lastError: this.state.lastError, status: this.state.status, lastSyncedAt: this.state.lastSyncedAt });
  subscribe(listener: () => void) { this.events.on('state', listener); return () => this.events.off('state', listener); }
  reportDelivery(status: string | null, message: string | null = null) { this.setState({ deliveryStatus: status, deliveryMessage: message }); }
  async lookupContact(id: string) { const jid = normalizeJid(id); const cached = this.contacts.get(jid); const socket = this.socket; if (!socket) return cached || null; const [result] = (await socket.onWhatsApp(jid)) || []; if (!result?.exists) return null; const imageUrl = (await socket.profilePictureUrl(jid, 'image').catch(() => cached?.imageUrl || null)) ?? null; const contact: Contact = { id: jid, name: cached?.name || null, notify: cached?.notify || null, verifiedName: cached?.verifiedName || null, imageUrl, updatedAt: new Date().toISOString() }; this.contacts.set(jid, contact); return contact; }
  async start() { if (this.socket || this.startPromise) return this.startPromise; this.startPromise = this.createSocket(); try { await this.startPromise; } catch (error) { this.setState({ status: 'error', lastError: error instanceof Error ? error.message : 'Unable to initialize WhatsApp' }); throw error; } finally { this.startPromise = null; } }
  private setState(patch: Partial<WhatsAppState>) { this.state = { ...this.state, ...patch, reconnectAttempts: this.reconnectAttempts, updatedAt: new Date().toISOString() }; this.events.emit('state'); }
  private clearQrTimer() { if (this.qrTimer) clearTimeout(this.qrTimer); this.qrTimer = null; }
  private async createSocket() { this.setState({ status: this.reconnectAttempts ? 'reconnecting' : 'initializing', lastError: null, qr: null, qrExpiresAt: null }); await mkdir(authDirectory(), { recursive: true }); const { state, saveCreds } = await useMultiFileAuthState(authDirectory()); this.setState({ status: 'loading' }); const { version } = await fetchLatestBaileysVersion(); const quietLogger = { child: () => quietLogger, trace() {}, debug() {}, info() {}, warn() {}, error() {}, fatal() {} }; const socket = makeWASocket({ version, auth: { creds: state.creds, keys: makeCacheableSignalKeyStore(state.keys, quietLogger as any) }, browser: ['Fusion One', 'Chrome', '1.0.0'], markOnlineOnConnect: false, syncFullHistory: false, shouldIgnoreJid: jid => jid === 'status@broadcast' }); this.socket = socket; socket.ev.on('creds.update', saveCreds); this.bindEvents(socket); this.setState({ status: state.creds.registered ? 'authenticating' : 'waiting_for_qr', platformVersion: version.join('.') }); whatsappLog('info', 'socket_created'); }
  private bindEvents(socket: WASocket) { socket.ev.on('connection.update', async update => { if (socket !== this.socket) return; if (update.qr) { this.clearQrTimer(); const expiresAt = new Date(Date.now() + 55_000).toISOString(); this.setState({ status: 'qr_available', qr: await QRCode.toDataURL(update.qr, { margin: 1, width: 320 }), qrExpiresAt: expiresAt }); this.qrTimer = setTimeout(() => { if (this.state.status === 'qr_available') this.setState({ status: 'qr_expired', qr: null, qrExpiresAt: null }); }, 56_000); } if (update.connection === 'connecting' && this.state.status === 'qr_available') this.setState({ status: 'pairing' }); if (update.connection === 'open') { this.clearQrTimer(); this.reconnectAttempts = 0; const photo = await socket.profilePictureUrl(socket.user?.id || '', 'image').catch(() => null); this.setState({ status: 'connected', qr: null, qrExpiresAt: null, connectedAt: new Date().toISOString(), authenticatedAt: this.state.authenticatedAt || new Date().toISOString(), phone: socket.user?.id?.split(':')[0] || null, profileName: socket.user?.name || null, profilePhoto: photo, lastSyncedAt: new Date().toISOString(), lastError: null }); whatsappLog('info', 'connected'); } if (update.connection === 'close') { this.clearQrTimer(); const code = (update.lastDisconnect?.error as { output?: { statusCode?: number } } | undefined)?.output?.statusCode; this.socket = null; if (code === DisconnectReason.loggedOut || code === DisconnectReason.badSession) { await this.clearAuthentication(); this.setState({ status: code === DisconnectReason.badSession ? 'authentication_failed' : 'logged_out', qr: null, qrExpiresAt: null, lastError: 'Session requires pairing' }); return; } this.setState({ status: 'disconnected', qr: null, qrExpiresAt: null, lastError: code ? `Disconnected (${code})` : 'Disconnected' }); this.scheduleReconnect(); } }); socket.ev.on('contacts.upsert', contacts => { contacts.forEach(contact => this.upsertContact(contact)); this.setState({ lastSyncedAt: new Date().toISOString() }); }); socket.ev.on('contacts.update', contacts => contacts.forEach(contact => { if (contact.id) this.upsertContact(contact as { id: string; name?: string | null; notify?: string | null; verifiedName?: string | null; imgUrl?: string | null; }); })); socket.ev.on('messages.upsert', event => { event.messages.forEach(message => { if (message.key.id) this.messages.set(message.key.id, message); }); whatsappLog('info', 'messages_received', { type: event.type, count: event.messages.length }); }); socket.ev.on('presence.update', event => whatsappLog('info', 'presence_updated', { id: event.id })); }
  private upsertContact(contact: { id: string; name?: string | null; notify?: string | null; verifiedName?: string | null; imgUrl?: string | null }) { this.contacts.set(contact.id, { id: contact.id, name: contact.name || null, notify: contact.notify || null, verifiedName: contact.verifiedName || null, imageUrl: contact.imgUrl || null, updatedAt: new Date().toISOString() }); }
  private scheduleReconnect() { if (this.reconnectTimer || ['logged_out', 'authentication_failed'].includes(this.state.status)) return; const delay = Math.min(30_000, 1_000 * 2 ** Math.min(this.reconnectAttempts++, 5)); this.setState({ status: 'reconnecting' }); this.reconnectTimer = setTimeout(() => { this.reconnectTimer = null; void this.start().catch(error => whatsappLog('error', 'reconnect_failed', { message: error instanceof Error ? error.message : 'unknown' })); }, delay); }
  private requireSocket() { if (!this.socket || this.state.status !== 'connected') throw new Error('WhatsApp is not connected'); return this.socket; }
  private async quoted(id?: string): Promise<WAMessage | undefined> { if (!id) return undefined; const message = this.messages.get(id); if (!message) throw new Error('Quoted message is not available in the active session'); return message; }
  async sendText(input: SendTextInput) { const socket = this.requireSocket(); const result = await socket.sendMessage(normalizeJid(input.to), { text: input.text.slice(0, 4096) }, { quoted: await this.quoted(input.quotedMessageId) }); if (!result?.key.id) throw new Error('WhatsApp did not return a message id'); return result.key.id; }
  async sendMedia(input: SendMediaInput) { const socket = this.requireSocket(); const media = prepareMedia(input); const content = input.kind === 'image' ? { image: media.buffer, caption: media.caption } : { document: media.buffer, mimetype: media.mimeType, fileName: media.fileName, caption: media.caption }; const result = await socket.sendMessage(normalizeJid(input.to), content, { quoted: await this.quoted(input.quotedMessageId) }); if (!result?.key.id) throw new Error('WhatsApp did not return a message id'); return result.key.id; }
  async clearAuthentication() { await rm(authDirectory(), { recursive: true, force: true }); this.messages.clear(); this.contacts.clear(); }
  async logout() { if (this.reconnectTimer) clearTimeout(this.reconnectTimer); this.reconnectTimer = null; this.clearQrTimer(); const socket = this.socket; this.socket = null; if (socket) await socket.logout().catch(() => socket.end(undefined)); await this.clearAuthentication(); this.state = initialState(); this.setState({ status: 'logged_out' }); }
  async shutdown() { if (this.reconnectTimer) clearTimeout(this.reconnectTimer); this.clearQrTimer(); this.socket?.end(undefined); this.socket = null; this.setState({ status: 'disconnected', qr: null, qrExpiresAt: null }); }
}
const globalForWhatsApp = globalThis as typeof globalThis & { whatsappManager?: WhatsAppManager };
export const whatsappManager = globalForWhatsApp.whatsappManager ??= new WhatsAppManager();
